name: Playwright Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'

      - name: Build & Install
        run: mvn -B install -DskipTests --no-transfer-progress

      - name: Install Playwright Browsers
        run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install --with-deps"

      - name: Run TestNG Tests
        run: mvn test
        # If you use testng.xml, use this instead:
        # run: mvn test -Dsurefire.suiteXmlFiles=testng.xml

      - name: Upload Extent Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Extent-Report
          path: reports/
          if-no-files-found: ignore

      - name: Upload TestNG Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestNG-Report
          path: test-output/
          if-no-files-found: ignore

      - name: Upload Surefire Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Surefire-Report
          path: target/surefire-reports/
          if-no-files-found: ignore

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Screenshots
          path: screenshots/
          if-no-files-found: ignore

      - name: Upload Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Videos
          path: videos/
          if-no-files-found: ignore

      - name: Upload Traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Traces
          path: traces/
          if-no-files-found: ignore